package fling.grammars.api;

import static fling.grammars.api.BNFAPICompiler.parse_PlainBNF;

import fling.*;

/**
 * {@link BNF} builder API. Initially generated by Fling.
 * 
 * @author Ori Roth
 */
@SuppressWarnings("all") public interface BNFAPI {
  public enum Σ implements Terminal {
    bnf, start, derive, specialize, to, into, toEpsilon, or, orNone
  }

  public enum V implements Variable {
    PlainBNF, Rule, RuleBody, RuleTail
  }

  /**
   * Start specifying grammar.
   * 
   * @return BNF builder API
   */
  public static q0ø__Rule1$start_q0$q0ø<q0$_$_q0$<$>, $> bnf() {
    α α = new α();
    α.w.add(new fling.internal.compiler.Assignment(Σ.bnf));
    return α;
  }

  interface $ {
    BNF build();
  }

  interface q0$_$_q0$<q0$> extends $ {
  }

  interface q0ø__Rule1$start_q0$q0ø<q0$, q0ø> {
    q0$__Rule1$_q0$q0ø<q0$, q0ø> start(Variable variable);
  }

  interface q0$__Rule1$_q0$q0ø<q0$, q0ø> extends $ {
    q0ø__Rule1$RuleBody$_q0$q0ø<q0$, q0ø> derive(Variable variable);
    q0ø__Rule1$into_q0$q0ø<q0$, q0ø> specialize(Variable variable);
  }

  interface q0ø__Rule1$RuleBody$_q0$q0ø<q0$, q0ø> {
    q0$__RuleTail1$_derivespecializeq0$q0ø<q0ø__Rule1$RuleBody$_q0$q0ø<q0$, q0ø>, q0ø__Rule1$into_q0$q0ø<q0$, q0ø>, q0$__Rule1$_q0$q0ø<q0$, q0ø>, q0$__Rule1$_q0$q0ø<q0$, q0ø>> to(
        Symbol... symbols);
    q0$__Rule1$_q0$q0ø<q0$, q0ø> toEpsilon();
  }

  interface q0ø__Rule1$into_q0$q0ø<q0$, q0ø> {
    q0$__Rule1$_q0$q0ø<q0$, q0ø> into(Variable... variables);
  }

  interface q0$__RuleTail1$_derivespecializeq0$q0ø<derive, specialize, q0$, q0ø> extends $ {
    derive derive(Variable variable);
    specialize specialize(Variable variable);
    q0$__RuleTail1$_derivespecializeq0$q0ø<derive, specialize, q0$, q0ø> or(Symbol... symbols);
    q0$__RuleTail1$_derivespecializeq0$q0ø<derive, specialize, q0$, q0ø> orNone();
  }

  static class α implements $, q0$_$_q0$, q0ø__Rule1$start_q0$q0ø, q0$__Rule1$_q0$q0ø, q0ø__Rule1$RuleBody$_q0$q0ø,
      q0ø__Rule1$into_q0$q0ø, q0$__RuleTail1$_derivespecializeq0$q0ø {
    public java.util.List<fling.internal.compiler.Assignment> w = new java.util.LinkedList();

    public α bnf() {
      this.w.add(new fling.internal.compiler.Assignment(Σ.bnf, new Object[] {}));
      return this;
    }
    public α start(Variable variable) {
      this.w.add(new fling.internal.compiler.Assignment(Σ.start, new Object[] { variable }));
      return this;
    }
    public α derive(Variable variable) {
      this.w.add(new fling.internal.compiler.Assignment(Σ.derive, new Object[] { variable }));
      return this;
    }
    public α specialize(Variable variable) {
      this.w.add(new fling.internal.compiler.Assignment(Σ.specialize, new Object[] { variable }));
      return this;
    }
    public α into(Variable... variables) {
      this.w.add(new fling.internal.compiler.Assignment(Σ.into, new Object[] { variables }));
      return this;
    }
    public α to(Symbol... symbols) {
      this.w.add(new fling.internal.compiler.Assignment(Σ.to, new Object[] { symbols }));
      return this;
    }
    public α toEpsilon() {
      this.w.add(new fling.internal.compiler.Assignment(Σ.toEpsilon, new Object[] {}));
      return this;
    }
    public α or(Symbol... symbols) {
      this.w.add(new fling.internal.compiler.Assignment(Σ.or, new Object[] { symbols }));
      return this;
    }
    public α orNone() {
      this.w.add(new fling.internal.compiler.Assignment(Σ.orNone, new Object[] {}));
      return this;
    }
    public BNF build() {
      return BNF.toBNF(parse_PlainBNF(w));
    }
  }
}
