package org.spartan.fajita.api.bnf;

import java.util.List;
import java.util.Set;

import org.spartan.fajita.api.bnf.rules.DerivationRule;
import org.spartan.fajita.api.bnf.symbols.NonTerminal;
import org.spartan.fajita.api.bnf.symbols.Verb;

public final class BNF {
  private final Set<Verb> verbs;
  private final List<NonTerminal> nonterminals;
  private final List<DerivationRule> derivationRules;

  BNF(final BNFBuilder builder) {
    verbs = builder.getVerbs();
    nonterminals = builder.getNonTerminals();
    derivationRules = builder.getRules();
  }
  public List<NonTerminal> getNonTerminals() {
    return nonterminals;
  }
  public Set<Verb> getVerbs() {
    return verbs;
  }
  public static String getApiName() {
    return "AutoGeneratedStates";
  }
  @Override public String toString() {
    StringBuilder sb = new StringBuilder() //
        .append("Verbs set: " + getVerbs() + "\n") //
        .append("Nonterminals set: " + getNonTerminals() + "\n") //
        .append("Rules for " + getApiName() + ":\n");
    for (DerivationRule rule : getRules())
      sb.append(rule.toString() + "\n");
    return sb.toString();
  }
  public List<DerivationRule> getRules() {
    return derivationRules;
  }

  public static class ClassEllipsis {
    //
  }
}
