package org.spartan.fajita.api.examples.automatonCycles.states;

import java.lang.Integer;
import java.lang.Object;
import java.lang.Override;
import java.lang.RuntimeException;
import java.lang.String;
import java.lang.SuppressWarnings;
import java.util.ArrayList;
import java.util.List;
import org.spartan.fajita.api.Main;
import org.spartan.fajita.api.bnf.rules.DerivationRule;
import org.spartan.fajita.api.examples.ASTViewer;

@SuppressWarnings("unused") public class AutoGeneratedStates {
  @SuppressWarnings({ "all" }) interface IStack<Tail extends IStack> {
  }

  @SuppressWarnings({ "all" }) public static class EmptyStack implements IStack<EmptyStack> {
  }

  public static class ErrorState extends
      BaseState<EmptyStack, ErrorState, ErrorState, ErrorState, ErrorState, ErrorState, ErrorState, ErrorState, ErrorState> {
    ErrorState() {
      super(new EmptyStack(), null);
    }
  }

  @SuppressWarnings({ "serial" }) public static class ParseError extends RuntimeException {
    ParseError(final String msg) {
      super(msg);
    }
  }

  @SuppressWarnings({
      "rawtypes" }) public abstract static class BaseState<Stack extends IStack<?>, a3988 extends BaseState, b4019 extends BaseState, d692408147 extends BaseState, d1418485606 extends BaseState, A extends BaseState, B extends BaseState, C extends BaseState, D extends BaseState>
          implements IStack<Stack> {
    private final Stack stack;
    protected final List<DerivationRule> reduces;

    BaseState(final Stack stack, final List<DerivationRule> reduces) {
      this.stack = stack;
      this.reduces = reduces;
    }
    protected Stack pop() {
      return stack;
    }
    protected a3988 a() {
      throw new ParseError("unexpected symbol on state " + getClass().getSimpleName());
    }
    protected b4019 b() {
      throw new ParseError("unexpected symbol on state " + getClass().getSimpleName());
    }
    protected d692408147 d(String arg0) {
      throw new ParseError("unexpected symbol on state " + getClass().getSimpleName());
    }
    protected d1418485606 d(Integer arg0) {
      throw new ParseError("unexpected symbol on state " + getClass().getSimpleName());
    }
    protected A A() {
      throw new ParseError("unexpected symbol on state " + getClass().getSimpleName());
    }
    protected B B() {
      throw new ParseError("unexpected symbol on state " + getClass().getSimpleName());
    }
    protected C C() {
      throw new ParseError("unexpected symbol on state " + getClass().getSimpleName());
    }
    protected D D() {
      throw new ParseError("unexpected symbol on state " + getClass().getSimpleName());
    }
    protected Object $() {
      throw new ParseError("unexpected symbol on state " + getClass().getSimpleName());
    }
  }

  public static class Q0 extends
      BaseState<EmptyStack, Q1<Q0, Q5<Q4<Q0, ?, ?>, Q8<Q2<Q0>>, Q7<Q2<Q0>>>>, ErrorState, ErrorState, ErrorState, Q4<Q0, Q8<Q2<Q0>>, Q7<Q2<Q0>>>, ErrorState, Q2<Q0>, Q3<Q0>> {
    public Q0() {
      super(new EmptyStack(), new ArrayList<>());
    }
    @Override public Q1<Q0, Q5<Q4<Q0, ?, ?>, Q8<Q2<Q0>>, Q7<Q2<Q0>>>> a() {
      return new Q1<>(this, reduces);
    }
    @Override protected Q4<Q0, Q8<Q2<Q0>>, Q7<Q2<Q0>>> A() {
      return new Q4<>(this, reduces);
    }
    @Override protected Q2<Q0> C() {
      return new Q2<>(this, reduces);
    }
    @Override protected Q3<Q0> D() {
      return new Q3<>(this, reduces);
    }
  }

  public static class Q1<Stack extends BaseState<?, ?, ?, ?, ?, ?, ?, ?, ?>, A_1_b_4019 extends BaseState<?, ?, ?, ?, ?, ?, ?, ?, ?>>
      extends
      BaseState<Stack, Q1<Q1<Stack, ?>, A_1_b_4019>, A_1_b_4019, ErrorState, ErrorState, Q9<Q1<Stack, ?>, A_1_b_4019>, ErrorState, ErrorState, ErrorState> {
    private final String rule4 = "4,<A>,%a%*-84:-19:0:5:115:114:0:19:106:97:118:97:46:117:116:105:108:46:65:114:114:97:121:76:105:115:116:120:-127:-46:29:-103:-57:97:-99:3:0:1:73:0:4:115:105:122:101:120:112:0:0:0:0:119:4:0:0:0:0:120*";

    Q1(Stack stack, List<DerivationRule> reduces) {
      super(stack, reduces);
    }
    @Override public Q1<Q1<Stack, ?>, A_1_b_4019> a() {
      return new Q1<>(this, reduces);
    }
    @Override @SuppressWarnings({ "unchecked" }) public A_1_b_4019 b() {
      reduces.add(DerivationRule.deserialize(rule4));
      return (A_1_b_4019) pop().A().b();
    }
    @Override protected Q9<Q1<Stack, ?>, A_1_b_4019> A() {
      return new Q9<>(this, reduces);
    }
  }

  public static class Q2<Stack extends BaseState<?, ?, ?, ?, ?, ?, ?, ?, ?>> extends
      BaseState<Stack, ErrorState, ErrorState, Q7<Q2<Stack>>, Q8<Q2<Stack>>, ErrorState, ErrorState, ErrorState, ErrorState> {
    Q2(Stack stack, List<DerivationRule> reduces) {
      super(stack, reduces);
    }
    @Override public Q7<Q2<Stack>> d(String arg0) {
      return new Q7<>(this, reduces);
    }
    @Override public Q8<Q2<Stack>> d(Integer arg0) {
      return new Q8<>(this, reduces);
    }
  }

  public static class Q3<Stack extends BaseState<?, ?, ?, ?, ?, ?, ?, ?, ?>>
      extends BaseState<Stack, ErrorState, ErrorState, ErrorState, ErrorState, ErrorState, ErrorState, ErrorState, ErrorState> {
    Q3(Stack stack, List<DerivationRule> reduces) {
      super(stack, reduces);
    }
    @Override public Object $() {
      ASTViewer.showASTs(Main.generateAST(reduces));
      System.out.println("finished");
      return new Object();
    }
  }

  public static class Q4<Stack extends BaseState<?, ?, ?, ?, ?, ?, ?, ?, ?>, C_1_d_1418485606 extends BaseState<?, ?, ?, ?, ?, ?, ?, ?, ?>, C_1_d_692408147 extends BaseState<?, ?, ?, ?, ?, ?, ?, ?, ?>>
      extends
      BaseState<Stack, ErrorState, Q5<Q4<Stack, ?, ?>, C_1_d_1418485606, C_1_d_692408147>, ErrorState, ErrorState, ErrorState, Q6<Q4<Stack, ?, ?>, C_1_d_1418485606, C_1_d_692408147>, ErrorState, ErrorState> {
    Q4(Stack stack, List<DerivationRule> reduces) {
      super(stack, reduces);
    }
    @Override public Q5<Q4<Stack, ?, ?>, C_1_d_1418485606, C_1_d_692408147> b() {
      return new Q5<>(this, reduces);
    }
    @Override protected Q6<Q4<Stack, ?, ?>, C_1_d_1418485606, C_1_d_692408147> B() {
      return new Q6<>(this, reduces);
    }
  }

  public static class Q5<Stack extends BaseState<?, ?, ?, ?, ?, ?, ?, ?, ?>, B_1_d_1418485606 extends BaseState<?, ?, ?, ?, ?, ?, ?, ?, ?>, B_1_d_692408147 extends BaseState<?, ?, ?, ?, ?, ?, ?, ?, ?>>
      extends
      BaseState<Stack, ErrorState, ErrorState, B_1_d_692408147, B_1_d_1418485606, ErrorState, ErrorState, ErrorState, ErrorState> {
    private final String rule5 = "5,<B>,%b%*-84:-19:0:5:115:114:0:19:106:97:118:97:46:117:116:105:108:46:65:114:114:97:121:76:105:115:116:120:-127:-46:29:-103:-57:97:-99:3:0:1:73:0:4:115:105:122:101:120:112:0:0:0:0:119:4:0:0:0:0:120*";

    Q5(Stack stack, List<DerivationRule> reduces) {
      super(stack, reduces);
    }
    @Override @SuppressWarnings({ "unchecked" }) public B_1_d_692408147 d(String arg0) {
      reduces.add(DerivationRule.deserialize(rule5));
      return (B_1_d_692408147) pop().B().d(arg0);
    }
    @Override @SuppressWarnings({ "unchecked" }) public B_1_d_1418485606 d(Integer arg0) {
      reduces.add(DerivationRule.deserialize(rule5));
      return (B_1_d_1418485606) pop().B().d(arg0);
    }
  }

  public static class Q6<Stack extends BaseState<? extends BaseState<?, ?, ?, ?, ?, ?, ?, ?, ?>, ?, ?, ?, ?, ?, ?, ?, ?>, C_2_d_1418485606 extends BaseState<?, ?, ?, ?, ?, ?, ?, ?, ?>, C_2_d_692408147 extends BaseState<?, ?, ?, ?, ?, ?, ?, ?, ?>>
      extends
      BaseState<Stack, ErrorState, ErrorState, C_2_d_692408147, C_2_d_1418485606, ErrorState, ErrorState, ErrorState, ErrorState> {
    private final String rule2 = "2,<C>,<A>,<B>";

    Q6(Stack stack, List<DerivationRule> reduces) {
      super(stack, reduces);
    }
    @Override @SuppressWarnings({ "unchecked" }) public C_2_d_692408147 d(String arg0) {
      reduces.add(DerivationRule.deserialize(rule2));
      return (C_2_d_692408147) pop().pop().C().d(arg0);
    }
    @Override @SuppressWarnings({ "unchecked" }) public C_2_d_1418485606 d(Integer arg0) {
      reduces.add(DerivationRule.deserialize(rule2));
      return (C_2_d_1418485606) pop().pop().C().d(arg0);
    }
  }

  public static class Q7<Stack extends BaseState<? extends BaseState<?, ?, ?, ?, ?, ?, ?, ?, ?>, ?, ?, ?, ?, ?, ?, ?, ?>>
      extends BaseState<Stack, ErrorState, ErrorState, ErrorState, ErrorState, ErrorState, ErrorState, ErrorState, ErrorState> {
    private final String rule0 = "0,<D>,<C>,%d%*-84:-19:0:5:115:114:0:19:106:97:118:97:46:117:116:105:108:46:65:114:114:97:121:76:105:115:116:120:-127:-46:29:-103:-57:97:-99:3:0:1:73:0:4:115:105:122:101:120:112:0:0:0:1:119:4:0:0:0:1:118:114:0:16:106:97:118:97:46:108:97:110:103:46:83:116:114:105:110:103:-96:-16:-92:56:122:59:-77:66:2:0:0:120:112:120*";

    Q7(Stack stack, List<DerivationRule> reduces) {
      super(stack, reduces);
    }
    @Override public Object $() {
      reduces.add(DerivationRule.deserialize(rule0));
      return pop().pop().D().$();
    }
  }

  public static class Q8<Stack extends BaseState<? extends BaseState<?, ?, ?, ?, ?, ?, ?, ?, ?>, ?, ?, ?, ?, ?, ?, ?, ?>>
      extends BaseState<Stack, ErrorState, ErrorState, ErrorState, ErrorState, ErrorState, ErrorState, ErrorState, ErrorState> {
    private final String rule1 = "1,<D>,<C>,%d%*-84:-19:0:5:115:114:0:19:106:97:118:97:46:117:116:105:108:46:65:114:114:97:121:76:105:115:116:120:-127:-46:29:-103:-57:97:-99:3:0:1:73:0:4:115:105:122:101:120:112:0:0:0:1:119:4:0:0:0:1:118:114:0:17:106:97:118:97:46:108:97:110:103:46:73:110:116:101:103:101:114:18:-30:-96:-92:-9:-127:-121:56:2:0:1:73:0:5:118:97:108:117:101:120:114:0:16:106:97:118:97:46:108:97:110:103:46:78:117:109:98:101:114:-122:-84:-107:29:11:-108:-32:-117:2:0:0:120:112:120*";

    Q8(Stack stack, List<DerivationRule> reduces) {
      super(stack, reduces);
    }
    @Override public Object $() {
      reduces.add(DerivationRule.deserialize(rule1));
      return pop().pop().D().$();
    }
  }

  public static class Q9<Stack extends BaseState<? extends BaseState<?, ?, ?, ?, ?, ?, ?, ?, ?>, ?, ?, ?, ?, ?, ?, ?, ?>, A_2_b_4019 extends BaseState<?, ?, ?, ?, ?, ?, ?, ?, ?>>
      extends BaseState<Stack, ErrorState, A_2_b_4019, ErrorState, ErrorState, ErrorState, ErrorState, ErrorState, ErrorState> {
    private final String rule3 = "3,<A>,%a%*-84:-19:0:5:115:114:0:19:106:97:118:97:46:117:116:105:108:46:65:114:114:97:121:76:105:115:116:120:-127:-46:29:-103:-57:97:-99:3:0:1:73:0:4:115:105:122:101:120:112:0:0:0:0:119:4:0:0:0:0:120*,<A>";

    Q9(Stack stack, List<DerivationRule> reduces) {
      super(stack, reduces);
    }
    @Override @SuppressWarnings({ "unchecked" }) public A_2_b_4019 b() {
      reduces.add(DerivationRule.deserialize(rule3));
      return (A_2_b_4019) pop().pop().A().b();
    }
  }
}